// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCHEU2Q-DCOAjMNKz0qcVXOgw7QxIIRY',
    appId: '1:763665642686:web:91e54b624f7df833191aef',
    messagingSenderId: '763665642686',
    projectId: 'ecommerce-b2a77',
    authDomain: 'ecommerce-b2a77.firebaseapp.com',
    databaseURL: 'https://ecommerce-b2a77-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-b2a77.appspot.com',
    measurementId: 'G-7VKHDZY1LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSGR9L8EXxU88gaQamZdilTOu57mgst0',
    appId: '1:763665642686:android:69ba665accc9f47d191aef',
    messagingSenderId: '763665642686',
    projectId: 'ecommerce-b2a77',
    databaseURL: 'https://ecommerce-b2a77-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-b2a77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONu2ME0ZTk_T9bFv9kLH5rY8mxfv-2Xs',
    appId: '1:763665642686:ios:8f2c75d84d669c70191aef',
    messagingSenderId: '763665642686',
    projectId: 'ecommerce-b2a77',
    databaseURL: 'https://ecommerce-b2a77-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-b2a77.appspot.com',
    iosClientId: '763665642686-disei0rr51vbi3aebptlvuq9qkniaq0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.ecommerce-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONu2ME0ZTk_T9bFv9kLH5rY8mxfv-2Xs',
    appId: '1:763665642686:ios:eea7e0ff9b052cc1191aef',
    messagingSenderId: '763665642686',
    projectId: 'ecommerce-b2a77',
    databaseURL: 'https://ecommerce-b2a77-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-b2a77.appspot.com',
    iosClientId: '763665642686-bqfcrujdfeqf32uamv6fbs8b126j08lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
